# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-08 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180808_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reply',
            field=models.CharField(default='null', max_length=500),
        ),
    ]
