# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-08 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_post_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reply',
        ),
    ]
