# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-26 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20180726_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cmp_exp',
            field=models.IntegerField(default=0),
        ),
    ]
