# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-02 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_userprofile_cmp_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cmp_exp',
            field=models.IntegerField(),
        ),
    ]
