# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-07 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20180802_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cmp_exp',
            field=models.IntegerField(default=0),
        ),
    ]
